files:
  - source: /translations/en.lang.json
    translation: /translations/%two_letters_code%.lang.json

pull_request_title: "Update translations"

commit_message: "Update %language% translations"
append_commit_message: false