name: Crowdin Action

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  push:
    branches: [ main ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: crowdin
          create_pull_request: true
          pull_request_title: 'Update translations'
          pull_request_body: ''
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CROWDIN_PROJECT_ID: 750545
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}